### ISSUE TITLE
SubscriberConf QueueSize is not working

### ISSUE THREAD

**Issue by arboat** [aler9/goroslib#117]
## Which operating system are you using?

OS

- [ x] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [x ] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

Hello there, it seems  QueueSize in  SubscriberConf  is not working. I looked into codes and find this in  subscriber.go:

```
for {
			select {
			case msg := <-s.message:
				cbv.Call([]reflect.Value{reflect.ValueOf(msg)})
			case <-s.ctx.Done():
				return
			}
		}
```

I assume "cbv.Call" call the Callback in SubscriberConf, but this is called synchronously  whether setting QueueSize to zero or not
. And a simple go(goruntine) can solve the problem but I do not sure if this will cause more problems or there has better solutions. So Please help to check it out. Thank you very much.

```
case msg := <-s.message:
			go	cbv.Call([]reflect.Value{reflect.ValueOf(msg)})
```

**Comment by aler9** [comment]
Hello, this library follows the official ROS specifications, and if the specification isn't clear enough about a specific matter, it tries to mimic the official C++ library.

In the official C++ library, a subscriber receives messages sequentially, independently from queue_size. Subscriber callbacks are processed in the same thread. If you have a subscriber like this:

```cpp
#include <ros/ros.h>
#include <std_msgs/String.h>

void on_message(const std_msgs::String::ConstPtr& in) {
    printf("PRE-SLEEP\n");
    ros::Duration(5).sleep();
    printf("POST-SLEEP\n");
}

int main(int argc, char **argv) {
    ros::init(argc, argv, "nodesub");
    ros::NodeHandle node;
    auto sub = node.subscribe("/test_topic", 100, on_message);
    ros::spin();
    return 0;
}
```

And you publish something with:

```
rostopic pub -r 1 /test_topic std_msgs/String "testing"
```

The result will be

```
PRE-SLEEP
POST-SLEEP
PRE-SLEEP
POST-SLEEP
PRE-SLEEP
POST-SLEEP
```

Therefore, callbacks are called sequentially.

`QueueSize` is used to queue incoming messages in order to discard some messages when the subscriber can't keep up with the message rate. It doesn't influence the number of threads. The [wiki](http://wiki.ros.org/roscpp/Overview/Publishers%20and%20Subscribers#Queueing_and_Lazy_Deserialization) says:

> When a message first arrives on a topic it gets put into a queue whose size is specified by the queue_size parameter in subscribe(). If the queue is full and a new message arrives, the oldest message will be thrown out. Additionally, the message is not actually deserialized until the first callback which needs it is about to be called. 

If you want to handle messages concurrently, just instantiate multiple subscribers.
